#!/usr/bin/env bash
# Rebuild every asset in assets/ from source-of-truth generators + ImageMagick.
set -e
cd "$(dirname "${BASH_SOURCE[0]}")"
echo "🔨 DEEPDIG asset forge"
rm -rf ../assets/tiles ../assets/fx ../assets/sprites ../assets/ui ../assets/bg
python3 gen_tiles.py
python3 gen_sprites.py
python3 gen_font.py
python3 gen_ui.py
python3 gen_bg.py
echo "✅ $(find ../assets -name '*.png' | wc -l) PNG files → $(du -sh ../assets | cut -f1)"

# generate the runtime asset manifest (no fetch() at runtime → works from file://)
{
  echo "/* generated by tools/build_assets.sh — do not edit by hand */"
  echo "window.DG = window.DG || {};"
  echo -n "DG.ASSET_LIST = ["
  (cd .. && find assets -name '*.png' | sort | sed 's/^/"/; s/$/",/' | tr -d '\n')
  echo "];"
} > ../js/assetlist.js
echo "📜 js/assetlist.js → $(grep -o '",' ../js/assetlist.js | wc -l) entries"
